# Site Settings
title: Marc Körner
#url: 'http://webjeda.com'
#baseurl: '/online-cv' #change it according to your repository name
#about: True # set to False or comment line if you want to remove the "How to use?" in the sidebar


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name: Marc Körner
tagline: Postdoctoral Researcher
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: 'I am currently working as a postdoctoral DAAD scholar at the <a href="http://www.icsi.berkeley.edu/icsi/">ICSI</a>, the UC Berkeley <a href="https://netsys.cs.berkeley.edu/">Netsys Lab</a> group, and the EIT Digital <a href="https://www.eitdigital.eu/about-us/locations/silicon-valley-hub/">Silicon Vally hub</a>. I received a Dr.-Ing. degree (PhD equivalent) from the faculty of CS and EE at TU Berlin in 2015, while I was working for the <a href="http://www.cit.tu-berlin.de/menue/complex_and_distributed_it_systems/">Complex and Distributed IT Systems</a> department. My research focus is in scope of network technologies and SDN/NFV based data center solutions. I have almost 6 years experiences in EU research projects as well as an industrial background.'

#sidebar links
email: koerner@ICSI.Berkeley.EDU
#phone: 012 345 6789
#website: blog.webjeda.com #do not add http://
linkedin: marc-körner-71a13593
github: marckoerner
#twitter: '@webjeda'
#Update all the sections by editing the files inside _data folder.

# uncomment the next line, if you want the education section displayed in main instead of the sidebar
#education_in_main: True

# Tracker
analytics: UA-83979019-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
